# Pengenalan NumPy

`NumPy` merupakan library python yang digunakan untuk membuat data array. Ada beberapa manfaat `Numpy` diantaranya:
* Dapat membuat array multidimensi
* Dapat diubah menjadi tipe data frame

In [12]:
import numpy as np #231061006, ANDI OXY RAIHAN

a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape
(1, 6)

(1, 6)

In [15]:
arr = np.array([[5],
                [6],
                [7],
                [8]])
arr

array([[5],
       [6],
       [7],
       [8]])

In [5]:
#Membuat Array Dasar
a = np.array([1, 2, 3, 4, 5, 6])
print(a[0])

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[0])

a = np.array([1, 2, 3])

np.zeros(2)

print(np.ones(5))

np.empty(2)

np.arange(4)

np.arange(2, 9, 2)

np.linspace(0, 10, num=5)

x = np.ones(2, dtype=np.int64)

1
[1 2 3 4]
[1. 1. 1. 1. 1.]


In [24]:
#Menambah, Menghapus, dan Menyortir elemen
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y), axis=0)

#Cara mengetahui bentuk dan ukuran Array
array_example = np.array([[[0, 1, 2, 3], [4, 5, 6, 7]],

                          [[0, 1, 2, 3], [4, 5, 6, 7]],
                          
                          [[0 ,1 ,2, 3], [4, 5, 6, 7]]])
print(array_example.ndim)
print(array_example.size)
print(array_example.shape)

print(array_example[0,1,2])

3
24
(3, 2, 4)
6


In [18]:


# #Mengubah Bentuk Array
# a = np.arange(6)
# print(a)

# b = a.reshape(3, 2)
# print(b)

# np.reshape(a, newshape=(1, 6), order='C')

# #Mengubah Array 1D menjadi Array 2D (Menambah Axis Baru)
# a = np.array([1, 2, 3, 4, 5, 6])
# a.shape

# a2 = a[np.newaxis, :]
# a2.shape

# row_vector = a[np.newaxis, :]
# row_vector.shape

# col_vector = a[:, np.newaxis]
# col_vector.shape

# a = np.array([1, 2, 3, 4, 5, 6])
# a.shape

# b = np.expand_dims(a, axis=1)
# b.shape

# c = np.expand_dims(a, axis=0)
# c.shape

# #indeks dan Irisan
# data = np.array([1, 2, 3])
# data[1]

# data[0:2]
# array(1,2)
# data[1:]
# array([2, 3])
# data[-2:]
# array([2, 3])

# a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# print(a[a < 5])

# five_up = (a >= 5)
# print(a[five_up])

# divisible_by_2 = a[a%2==0]
# print(divisible_by_2)

# c = a[(a > 2) & (a < 11)]
# print(c)

# five_up = (a > 5) | (a == 5)
# print(five_up)

# a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# b = np.nonzero(a < 5)
# print(b)

# list_of_coordinates= list(zip(b[0], b[1]))
# for coord in list_of_coordinates:
#   print(coord)

# print(a[b])

# not_there = np.nonzero(a == 42)
# print(not_there)

(3, 2, 4)

In [ ]:
#Membuat Array dari data yang sudah ada
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr1 = a[3:8]
arr1

a1 = np.array([[1, 1],
              [2, 2]])
a2 = np.array([[3, 3],
              [4, 4]])
np.vstack((a1, a2))

np.hstack((a1, a2))

x = np.arange(1, 25).reshape(2, 12)
x

np.hsplit(x, 3)
np.hsplit(x, (3, 4))

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b1 = a[0, :]
b1

b1[0] = 99
b1
a
b2 = a.copy()

In [ ]:
#Operasi Dasar Array
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones
data - ones
data * data
data / data

a = np.array([1, 2, 3, 4])
a.sum()

b = np.array([[1, 1], [2, 2]])
b.sum(axis=0)
b.sum(axis=1)

In [ ]:
#Penyiaran
data = np.array([1.0, 2.0])
data * 1.6

#Operasi Array Yang Lebih Berguna
data.max()

data.min()

data.sum()

a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])
a.sum()
a.min()
a.min(axis=0)

In [ ]:
#Membuat Matriks
data = np.array([[1, 2], [3, 4], [5, 6]])
data

data[0,1]
data[1:3]
data[0:2, 0]

data.max()
data.min()
data.sum()

data = np.array([[1, 2], [5, 3], [4, 6]])
data
data.max(axis=0)
data.max(axis=1)

data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

np.ones((4, 3, 2))
np.ones(3)
np.zeros(3)

rng = np.random.default_rng()
rng.random(3)

np.ones ((3,2))
np.zeros ((3,2))
rng.random ((3,2))

In [ ]:
#Membuat Angka Acak
rng.integers(5, size=(2, 4))

#Cara mendapatkan item unik dan menghitungnya
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
unique_values = np.unique(a_2d)
print(unique_values)

unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

unique_rows, indices, occurrence_count = np.unique(a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)
print(indices)
print(occurrence_count)

In [ ]:
#Matriks Transpose
data.reshape(2, 3)
data.reshape(3, 2)

arr = np.arange(6).reshape((2, 3))
arr

arr.transpose()

arr.T

#Membalikkan Array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print('Reversed Array: ', reversed_arr)
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

reversed_arr = np.flip(arr_2d)
print(reversed_arr)

reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

#Membentuk kembali dan meratakan array multidimensi
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()

a1 = x.flatten()
a1[0] = 99
print(x)
print(a1)

a2 = x.ravel()
a2[0] = 98
print(x)
print(a2)

In [ ]:
#Mengakses Docstring untuk Informasi lebih lanjut
help(max)
In [0]: max?

a = np.array([1, 2, 3, 4, 5, 6])
In [1]: a?

def double(a):
  return a * 2

In [2]: double?
In [3]: double??
In [4]: len?
In [5]: len??

In [ ]:
#Menggunakan formula matematika
error = (1/n)*np.sum(np.square(predictions-labels))
error = (1/3)*np.sum(np.square)

In [ ]:
#Cara menyimpan dan membuka Objek NumPy
a = np.array([1, 2, 3, 4, 5, 6])
np.save('filename', a)

b = np.load('filename.npy')
print(b)

csv_arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.savetxt('new_file.csv', csv_arr)

 np.loadtxt('new_file.csv')

In [ ]:
import pandas as pd #Import dan export csv
x = pd.read_csv('music.csv', header=0).values
print(x)

x = pd.read_csv('music.csv', usecols=['Artist', 'Plays']).values
print(x)

a = np.array([[-2.58289208, 0.43014843, -1.24082018, 1.59572603],
              [ 0.99027828, 1.17150989, 0.94125714, -0.14692469],
              [ 0.76989341, 0.81299683, -0.95068423, 0.11769564],
              [ 0.20484034, 0.34784527, 1.96979195, 0.51992837]])
df = pd.DataFrame(a)
print(df)

df.to_csv('pd.csv')

data = pd.read_csv('pd.csv')

np.savetxt('np.csv', a, fmt='%.2f', delimiter=',', header='1, 2, 3, 4')

In [ ]:
#Membuat Plot dengan Matplotlib
import matplotlib.pyplot as plt

a = np.array([2, 1, 5, 7, 4, 6, 8, 14, 10, 9, 18, 20, 22])
plt.plot(a)

In [ ]:
x = np.linspace(0, 5, 20)
y = np.linspace(0, 10, 20)
plt.plot(x, y, 'purple')
plt.plot(x, y, 'o')

In [ ]:
fig = plt.figure()
ax = fig.add_subplot(projection='3d')
X = np.arange(-5, 5, 0.15)
Y = np.arange(-5, 5, 0.15)
X, Y = np.meshgrid(X, Y)
R = np.sqrt(X**2 + Y**2)
Z = np.sin(R)
ax.plot_surface(X, Y, Z, rstride=1, cstride=1, cmap='viridis')